# Generated by Django 6.0.4 on 2026-05-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=30)),
                ('segmento', models.CharField(choices=[('agro', 'Agronegócio'), ('logistica', 'Logística'), ('industria', 'Indústria'), ('varejo', 'Varejo'), ('outro', 'Outro')], max_length=50)),
                ('desafio', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
