# Generated by Django 6.0.4 on 2026-05-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_alter_lead_options_lead_ip_lead_user_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="user_agent",
            field=models.TextField(blank=True, null=True, verbose_name="User Agent"),
        ),
    ]
